"""
ChromaDB vector store wrapper.

Each medical document is stored as:
  - text:      the full document content (used for semantic similarity search)
  - metadata:  structured fields for exact filtering (patient_name, date, doc_type, etc.)
  - id:        a stable hash of the file path (avoids duplicates on re-ingest)

Query flow:
  1. Optional metadata WHERE filter narrows the search space (fast, exact)
  2. Semantic similarity on the query embedding finds the most relevant chunks
"""
import logging
import time
import chromadb
from chromadb.utils.embedding_functions import SentenceTransformerEmbeddingFunction
from config import settings

logger = logging.getLogger(__name__)

# ── BM25 index (rebuilt lazily from ChromaDB) ─────────────────────────────────
# Stored at module level — survives across requests within one process.
# Reset to None whenever documents are added so the next search triggers a rebuild.
_bm25_index:   object    = None
_bm25_doc_ids: list[str] = []
_bm25_texts:   list[str] = []


def _invalidate_bm25() -> None:
    """Mark the BM25 index as stale — rebuilt automatically on next search."""
    global _bm25_index
    _bm25_index = None


def _build_bm25_index() -> None:
    """
    Build a BM25Okapi index from all documents currently in ChromaDB.
    Called lazily on the first BM25 search after startup or document addition.
    """
    global _bm25_index, _bm25_doc_ids, _bm25_texts

    try:
        from rank_bm25 import BM25Okapi
    except ImportError:
        logger.warning("rank-bm25 not installed — BM25 search disabled.")
        return

    collection = get_collection()
    count = collection.count()
    if count == 0:
        logger.info("BM25: collection empty — skipping index build")
        return

    logger.info("Building BM25 index from %d document(s)…", count)
    raw           = collection.get(include=["documents"])
    _bm25_doc_ids = raw["ids"]
    _bm25_texts   = raw["documents"]

    tokenized   = [text.lower().split() for text in _bm25_texts]
    _bm25_index = BM25Okapi(tokenized)
    logger.info("BM25 index ready — %d documents indexed", len(_bm25_doc_ids))


def _matches_filter(metadata: dict, where: dict) -> bool:
    """
    Evaluate a ChromaDB `where` filter against a metadata dict in pure Python.
    Supports $and, $or, $eq, $ne (covers all filters generated by intent_parser).
    """
    if "$and" in where:
        return all(_matches_filter(metadata, cond) for cond in where["$and"])
    if "$or" in where:
        return any(_matches_filter(metadata, cond) for cond in where["$or"])

    for field, condition in where.items():
        meta_val = str(metadata.get(field, ""))
        if isinstance(condition, dict):
            op, val = next(iter(condition.items()))
            if op == "$eq" and meta_val != str(val):
                return False
            if op == "$ne" and meta_val == str(val):
                return False
        else:
            if meta_val != str(condition):
                return False
    return True


def search_bm25(
    query_text:   str,
    where_filter: dict = None,
    n_results:    int  = 5,
) -> list[dict]:
    """
    BM25 keyword search over the entire document collection.

    Lazy-builds the in-memory index on the first call.
    Automatically rebuilds when _bm25_index is None (after any document add).

    Returns the same dict format as search() so results can be merged with RRF.
    """
    global _bm25_index, _bm25_doc_ids, _bm25_texts

    if _bm25_index is None:
        _build_bm25_index()

    if _bm25_index is None:
        return []  # rank-bm25 not installed or collection empty

    tokenized_query = query_text.lower().split()
    scores          = _bm25_index.get_scores(tokenized_query)
    max_score       = float(max(scores)) if max(scores) > 0 else 1.0

    sorted_indices = sorted(range(len(scores)), key=lambda i: scores[i], reverse=True)

    collection = get_collection()
    results: list[dict] = []

    for idx in sorted_indices:
        if len(results) >= n_results:
            break
        if scores[idx] <= 0:
            break

        doc_id = _bm25_doc_ids[idx]
        try:
            raw = collection.get(ids=[doc_id], include=["metadatas", "documents"])
            if not raw["ids"]:
                continue
            meta = raw["metadatas"][0]

            # Apply metadata filter in Python (BM25 has no native filter support)
            if where_filter and not _matches_filter(meta, where_filter):
                continue

            results.append({
                "id":              doc_id,
                "content":         raw["documents"][0],
                "metadata":        meta,
                "relevance_score": scores[idx] / max_score,
            })
        except Exception as exc:
            logger.warning("BM25 result fetch failed for %s: %s", doc_id, exc)

    return results


def _wait_for_chroma(host: str, port: int, retries: int = 20, delay: float = 3.0):
    """
    Block until ChromaDB's TCP port accepts connections.
    Uses a raw socket — no chromadb client — so it is version-independent.
    """
    import socket
    for attempt in range(1, retries + 1):
        try:
            sock = socket.create_connection((host, port), timeout=3)
            sock.close()
            logger.info("ChromaDB port is open.")
            # Give ChromaDB a moment to finish internal initialization
            # (tenant/database creation happens just after the port opens)
            time.sleep(5)
            return
        except OSError:
            logger.info("Waiting for ChromaDB... attempt %d/%d", attempt, retries)
            time.sleep(delay)
    raise RuntimeError(
        f"ChromaDB at {host}:{port} did not become ready after {retries} attempts."
    )


# Module-level singletons — created once, reused across requests
_client: chromadb.HttpClient = None
_collection = None


def get_collection():
    """Return the ChromaDB collection, connecting if not yet open."""
    global _client, _collection

    if _collection is not None:
        return _collection

    logger.info("Connecting to ChromaDB at %s:%s", settings.CHROMA_HOST, settings.CHROMA_PORT)

    # Wait for ChromaDB to be ready, then connect.
    # With matching server/client versions (both 0.5.3), the default_tenant
    # and default_database are created automatically on server startup.
    _wait_for_chroma(settings.CHROMA_HOST, settings.CHROMA_PORT)

    _client = chromadb.HttpClient(
        host=settings.CHROMA_HOST,
        port=settings.CHROMA_PORT,
    )

    # Sentence-transformer embedding model runs inside the backend container.
    # The model is downloaded on first use and cached in model_cache volume.
    ef = SentenceTransformerEmbeddingFunction(
        model_name=settings.EMBEDDING_MODEL
    )

    _collection = _client.get_or_create_collection(
        name=settings.CHROMA_COLLECTION,
        embedding_function=ef,
        metadata={"hnsw:space": "cosine"},  # Cosine similarity for text
    )

    logger.info(f"Connected — collection '{settings.CHROMA_COLLECTION}' "
                f"has {_collection.count()} document(s)")
    return _collection


def add_documents_batch(ids: list, texts: list, metadatas: list, batch_size: int = 100) -> int:
    """
    Add multiple documents in batches — much faster than one call per document
    because the embedding model processes many texts at once.

    Args:
        ids:        List of stable document IDs.
        texts:      List of document texts to embed.
        metadatas:  List of metadata dicts.
        batch_size: How many documents to upsert per call (default 100).

    Returns:
        Number of documents successfully stored.
    """
    collection = get_collection()
    stored = 0

    for start in range(0, len(ids), batch_size):
        end = start + batch_size
        batch_ids   = ids[start:end]
        batch_texts = texts[start:end]
        batch_metas = [
            {k: str(v) if v is not None else "" for k, v in m.items()}
            for m in metadatas[start:end]
        ]
        try:
            collection.upsert(
                ids=batch_ids,
                documents=batch_texts,
                metadatas=batch_metas,
            )
            stored += len(batch_ids)
            logger.info("Batch upsert: %d/%d documents stored", stored, len(ids))
        except Exception as e:
            logger.error("Batch upsert failed (rows %d-%d): %s", start, end, e)

    _invalidate_bm25()   # force BM25 rebuild on next search
    return stored


def add_document(doc_id: str, text: str, metadata: dict) -> bool:
    """
    Add (or replace) a document in the vector store.

    Args:
        doc_id:   Stable unique ID (MD5 of file path).
        text:     Full document text — will be embedded for similarity search.
        metadata: Dict of filterable fields. All values are coerced to str.

    Returns:
        True on success, False on error.
    """
    collection = get_collection()

    # ChromaDB requires metadata values to be str / int / float / bool
    clean_meta = {k: str(v) if v is not None else "" for k, v in metadata.items()}

    try:
        # upsert = insert or replace if id already exists
        collection.upsert(
            ids=[doc_id],
            documents=[text],
            metadatas=[clean_meta],
        )
        _invalidate_bm25()   # force BM25 rebuild on next search
        return True
    except Exception as e:
        logger.error(f"Failed to store document {doc_id}: {e}")
        return False


def search(
    query_text: str,
    where_filter: dict = None,
    n_results: int = 5,
) -> list[dict]:
    """
    Semantic search with optional metadata pre-filtering.

    Args:
        query_text:    The user's natural language query.
        where_filter:  ChromaDB `where` dict (exact match on metadata fields).
                       Example: {"$and": [{"doc_type": {"$eq": "bill"}},
                                          {"date":     {"$eq": "2025-10-27"}}]}
        n_results:     Maximum number of results to return.

    Returns:
        List of dicts — each with keys: id, content, metadata, relevance_score.
    """
    collection = get_collection()
    total = collection.count()

    if total == 0:
        logger.info("Vector store is empty — no results.")
        return []

    n_results = min(n_results, total)

    query_kwargs = {
        "query_texts": [query_text],
        "n_results": n_results,
        "include": ["documents", "metadatas", "distances"],
    }
    if where_filter:
        query_kwargs["where"] = where_filter

    try:
        raw = collection.query(**query_kwargs)
    except Exception as e:
        logger.warning(f"Search with filter failed ({e}); retrying without filter.")
        query_kwargs.pop("where", None)
        raw = collection.query(**query_kwargs)

    results = []
    for i in range(len(raw["ids"][0])):
        results.append({
            "id":              raw["ids"][0][i],
            "content":         raw["documents"][0][i],
            "metadata":        raw["metadatas"][0][i],
            # ChromaDB returns cosine distance (0 = identical, 2 = opposite)
            # Convert to similarity score 0–1
            "relevance_score": max(0.0, 1.0 - raw["distances"][0][i]),
        })

    return results


def list_all_documents() -> list[dict]:
    """Return every document currently in the vector store (metadata only)."""
    collection = get_collection()

    if collection.count() == 0:
        return []

    raw = collection.get(include=["metadatas", "documents"])
    docs = []
    for i, doc_id in enumerate(raw["ids"]):
        docs.append({
            "id":              doc_id,
            "metadata":        raw["metadatas"][i],
            "content_preview": raw["documents"][i][:300] + "…",
        })
    return docs


def delete_document(doc_id: str) -> bool:
    """Remove a document from the vector store by its ID."""
    try:
        get_collection().delete(ids=[doc_id])
        return True
    except Exception as e:
        logger.error(f"Failed to delete document {doc_id}: {e}")
        return False


def get_document_count() -> int:
    """Return the total number of documents in the store."""
    return get_collection().count()
